tasks:
  - before: >
      wget -qOdatabase-setup.sh https://codejudge-starter-repo-artifacts.s3.ap-south-1.amazonaws.com/backend-project/gitpod/python/3.5/db-gitpod-setup.sh &&
      chmod 0755 database-setup.sh &&
      bash database-setup.sh
    init: |
      pip install --upgrade pip
      python -m pip install Django==2.0 pytz==2019.2
      pip install -r requirements.txt
      python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8080
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-python.python
